mixed-port: 7890
allow-lan: false
bind-address: '*'
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
hosts:
  'mtalk.google.com': 108.177.125.188
  'dl.google.com': 180.163.151.161
  'dl.l.google.com': 180.163.151.161
profile:
  store-selected: false
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - 'time.windows.com'
    - 'time.nist.gov'
    - 'time.apple.com'
    - 'time.asia.apple.com'
    - '*.ntp.org.cn'
    - '*.openwrt.pool.ntp.org'
    - 'time1.cloud.tencent.com'
    - 'time.ustc.edu.cn'
    - 'pool.ntp.org'
    - 'ntp.ubuntu.com'
    - 'ntp.aliyun.com'
    - 'ntp1.aliyun.com'
    - 'ntp2.aliyun.com'
    - 'ntp3.aliyun.com'
    - 'ntp4.aliyun.com'
    - 'ntp5.aliyun.com'
    - 'ntp6.aliyun.com'
    - 'ntp7.aliyun.com'
    - 'time1.aliyun.com'
    - 'time2.aliyun.com'
    - 'time3.aliyun.com'
    - 'time4.aliyun.com'
    - 'time5.aliyun.com'
    - 'time6.aliyun.com'
    - 'time7.aliyun.com'
    - '*.time.edu.cn'
    - 'time1.apple.com'
    - 'time2.apple.com'
    - 'time3.apple.com'
    - 'time4.apple.com'
    - 'time5.apple.com'
    - 'time6.apple.com'
    - 'time7.apple.com'
    - 'time1.google.com'
    - 'time2.google.com'
    - 'time3.google.com'
    - 'time4.google.com'
    - 'music.163.com'
    - '*.music.163.com'
    - '*.126.net'
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    - '*.kuwo.cn'
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    - 'y.qq.com'
    - '*.y.qq.com'
    - 'streamoc.music.tc.qq.com'
    - 'mobileoc.music.tc.qq.com'
    - 'isure.stream.qqmusic.qq.com'
    - 'dl.stream.qqmusic.qq.com'
    - 'aqqmusic.tc.qq.com'
    - 'amobile.music.tc.qq.com'
    - '*.xiami.com'
    - '*.music.migu.cn'
    - 'music.migu.cn'
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - 'localhost.ptlogin2.qq.com'
    - '*.*.*.srv.nintendo.net'
    - '*.*.stun.playstation.net'
    - 'xbox.*.*.microsoft.com'
    - '*.*.xboxlive.com'
    - '*.taobao.com'
    - '*.*.taobao.com'
    - '*.*.*.taobao.com'
    - 'taobao.com'
    - '*.alicdn.com'
    - '*.mcdn.bilivideo.cn'
  nameserver:
    - https://1.12.12.12/dns-query
  fallback:
    - 'https://1.1.1.1/dns-query#全球加速'
    - 'https://doh.dns.sb/dns-query#全球加速'
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
proxies:

proxy-providers:
  #https://sub.v1.mk/
  HK:
    type: http
    url: ""
    #include: .*(香港); exclude: .*(游戏|马来|土耳其)
    interval: 86400
    path: ./HKList.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  HK-F:
    type: http
    url: " "
    #include: .*(香港); exclude: .*(游戏|马来|土耳其|香港7]|香港7-2|香港MS2|香港MS1|港企宽]福建|香港3|香港8|香港9)
    interval: 86400
    path: ./HKFList.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  PO-C:
    type: http
    url: ""
    #include: .*(印度|荷兰|美国6|越南1|泰国1|印尼|台湾2|港Anycast]海南)
    interval: 86400
    path: ./POCList.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  TW:
    type: http
    url: ""
    #include: .*(台湾); exclude: .*(游戏|隐私)
    interval: 86400
    path: ./TWList.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  SG:
    type: http
    url: ""
    #include: .*(新加); exclude: .*(游戏)
    interval: 86400
    path: ./SGList.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  JP:
    type: http
    url: ""
    #include: .*(日本); exclude: .*(游戏|隐私|阿根廷)
    interval: 86400
    path: ./JPList.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  US:
    type: http
    url: ""
    #include: .*(美国); exclude: .*(游戏|隐私)
    interval: 86400
    path: ./USList.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  PR:
    type: http
    url: ""
    #include: .*(隐私)
    interval: 86400
    path: ./PRList.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  KR:
    type: http
    url: ""
    #include: .*(韩); exclude: .*(游戏|隐私)
    interval: 86400
    path: ./KRList.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  SP:
    type: http
    url: ""
    #exclude: .*(游戏|香港|日本|新加|韩|台湾|美国)
    interval: 86400
    path: ./SPList.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
proxy-groups:
  - { name: 全球加速, type: select, proxies: [香港标准节点, 香港节点, 台湾节点, 日本节点, 新加坡隐私节点, 美国节点, DIRECT] }
  - { name: 国内媒体, type: select, proxies: [DIRECT, 香港标准节点, 香港节点, 台湾节点, 日本节点] }
  - { name: 国际媒体, type: select, proxies: [全球加速, 香港标准节点, 香港节点, 台湾节点, 日本节点, 新加坡隐私节点, 美国节点] }
  - { name: 游戏加速, type: select, proxies: [全球加速, 特惠节点, DIRECT, 香港标准节点, 香港节点, 台湾节点, 日本节点, 新加坡隐私节点, 美国节点] }
  - { name: 游戏下载, type: select, proxies: [特惠节点, DIRECT, 全球加速] }
  - { name: Speedtest, type: select, proxies: [全球加速, DIRECT, 香港标准节点, 香港节点, 台湾节点, 日本节点, 新加坡隐私节点, 美国节点] }
  - { name: Telegram, type: select, proxies: [隐私节点, 全球加速, DIRECT] }
  - { name: Microsoft, type: select, proxies: [DIRECT, 特惠节点, 全球加速, 新加坡隐私节点] }
  - { name: Bing, type: select, proxies: [DIRECT, 特惠节点, 全球加速, 新加坡隐私节点] }
  - { name: Apple, type: select, proxies: [DIRECT, 特惠节点, 全球加速, 新加坡隐私节点] }
  - { name: 香港节点, type: url-test, use: [HK], url: 'http://www.gstatic.com/generate_204', interval: 600 }
  - { name: 香港标准节点, type: url-test, use: [HK-F], url: 'http://www.gstatic.com/generate_204', interval: 600 }
  - { name: 台湾节点, type: url-test, use: [TW], url: 'http://www.gstatic.com/generate_204', interval: 600 }
  - { name: 日本节点, type: url-test, use: [JP], url: 'http://www.gstatic.com/generate_204', interval: 600 }
  - { name: 新加坡隐私节点, type: url-test, use: [SG], url: 'http://www.gstatic.com/generate_204', interval: 600 }
  - { name: 韩国节点, type: url-test, use: [KR], url: 'http://www.gstatic.com/generate_204', interval: 600 }
  - { name: 美国节点, type: url-test, use: [US], url: 'http://www.gstatic.com/generate_204', interval: 600 }
  - { name: 隐私节点, type: url-test, use: [PR], url: 'http://www.gstatic.com/generate_204', interval: 600 }
  - { name: 特惠节点, type: url-test, use: [PO-C], url: 'http://www.gstatic.com/generate_204', interval: 600 }
  - { name: 其他节点, type: select, use: [SP], url: 'http://www.gstatic.com/generate_204', interval: 600 }

rule-providers: 
  Unbreak:
    type: http
    behavior: classical
    path: "./rule_provider/Direct.yaml"
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.yaml
    interval: 86400
  Hijacking:
    type: http
    behavior: classical
    path: "./rule_provider/Hijacking.yaml"
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Guard/Hijacking.yaml
    interval: 86400
  Privacy:
    type: http
    behavior: classical
    path: "./rule_provider/Privacy.yaml"
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Privacy/Privacy.yaml
    interval: 86400
  Streaming:
    type: http
    behavior: classical
    path: "./rule_provider/Streaming.yaml"
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml
    interval: 86400
  StreamingSE:
    type: http
    behavior: classical
    path: "./rule_provider/StreamingSE.yaml"
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingSE.yaml
    interval: 86400
  Global:
    type: http
    behavior: classical
    path: "./rule_provider/Global.yaml"
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Global.yaml
    interval: 86400
  China:
    type: http
    behavior: classical
    path: "./rule_provider/China.yaml"
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml
    interval: 86400
  ChinaMax_Classical:
    type: http
    behavior: classical
    path: "./rule_provider/ChinaMax_Classical.yaml"
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Classical.yaml
    interval: 86400
  Speedtest:
    type: http
    behavior: classical
    path: "./rule_provider/speedtest.yaml"
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.yaml
    interval: 86400
  Telegram:
    type: http
    behavior: classical
    path: "./rule_provider/Telegram.yaml"
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Telegram/Telegram.yaml
    interval: 86400
  Game:
    type: http
    behavior: classical
    path: "./rule_provider/Game.yaml"
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.yaml
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    path: "./rule_provider/Microsoft.yaml"
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
    interval: 86400
  Bing:
    type: http
    behavior: classical
    path: "./rule_provider/Bing.yaml"
    url: https://ghproxy.com/https://raw.githubusercontent.com/Toyro7356/Clash/release/Rules/Bing.yaml
    interval: 86400
  Apple:
    type: http
    behavior: classical
    path: "./rule_provider/Apple.yaml"
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml
    interval: 86400
  GameDownload:
    type: http
    behavior: classical
    path: "./rule_provider/GameDownload.yaml"
    url: https://ghproxy.com/https://raw.githubusercontent.com/Toyro7356/Clash/release/Rules/GameDownload.yaml
    interval: 86400
  Taobao:
    type: http
    behavior: classical
    path: "./rule_provider/Taobao.yaml"
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Alibaba/Alibaba.yaml
    interval: 86400
  Special-Direct:
    type: http
    behavior: classical
    path: "./rule_provider/Special-Direct.yaml"
    url: https://ghproxy.com/https://raw.githubusercontent.com/Toyro7356/Clash/release/Rules/Special-Direct.yaml
    interval: 86400
  Special-Proxy:
    type: http
    behavior: classical
    path: "./rule_provider/Special-Proxy.yaml"
    url: https://ghproxy.com/https://raw.githubusercontent.com/Toyro7356/Clash/release/Rules/Special-Proxy.yaml
    interval: 86400
rules:
  - DOMAIN,lens.l.google.com,美国节点
  - RULE-SET,Special-Direct,DIRECT
  - RULE-SET,Special-Proxy,全球加速
  - RULE-SET,Privacy,REJECT
  - RULE-SET,Hijacking,REJECT
  - RULE-SET,Unbreak,DIRECT
  - RULE-SET,Taobao,DIRECT
  - RULE-SET,Bing,Bing
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,GameDownload,游戏下载
  - RULE-SET,Game,游戏加速
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Speedtest,Speedtest
  - RULE-SET,Apple,Apple
  - RULE-SET,StreamingSE,国内媒体
  - RULE-SET,Streaming,国际媒体
  - RULE-SET,China,DIRECT
  - RULE-SET,ChinaMax_Classical,DIRECT
  - RULE-SET,Global,全球加速
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT
  - IP-CIDR,fe80::/10,DIRECT
  - IP-CIDR,119.28.28.28/32,DIRECT
  - IP-CIDR,182.254.116.0/24,DIRECT
  - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
  - GEOIP,CN,DIRECT
  - MATCH,全球加速
