port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
authentication:
  - "HelloWorld:p4!3!BnfzU*Yq9F9"
geodata-mode: false
geodata-loader: memconservative
tcp-concurrent: true                    #【Meta专属】TCP连接并发，如果域名解析结果对应多个IP，并发所有IP，选择握手最快的IP进行连接
allow-lan: true                         #允许局域网连接(false/true)
bind-address: "*"                       #监听IP白名单（当allow-lan：true）
mode: rule                              #clash工作模式（rule/global/direct,meta暂不支持script）
log-level: silent                       #日志等级（info/warning/error/debug/silent）
ipv6: false                             #ip6开关，当为false时，停止解析hostanmes为ip6地址
external-controller: 127.0.0.1:9090     #控制器监听地址
secret: "123456"
external-ui: "/usr/share/openclash/ui"
profile:                                #缓存设置(文件位置./cache.db)
  store-selected: true                  #节点状态记忆
  store-fake-ip: true                   #fake-ip缓存
tun:
  enable: true
  stack: system
  device: meta
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
    - tcp://any:53
sniffer:                                #【Meta专属】sniffer域名嗅探器
  enable: true                          #嗅探开关
  sniffing:                             #嗅探协议对象：目前支持tls/http
    - tls
    - http
  skip-domain:                          #列表中的sni字段，保留mapping结果，不通过嗅探还原域名,优先级比force-domain高 
    - 'Mijia Cloud'                     #米家设备，建议加
    - 'dlg.io.mi.com'
    - '+.apple.com'                     #苹果域名，建议加
    - '+.jd.com'
    - '+.taobao.com'
  force-domain:                         #需要强制嗅探的域名，默认只对IP嗅探
  # - '+'                               #去掉注释后等于全局嗅探
    - 'google.com'
    - '+.netflix.com'
    - '+.nflxvideo.net'
    - '+.amazonaws.com'
    - '+.media.dssott.com'
  port-whitelist:                       #端口白名单，只对名单内的端口进行还原域名
    - 443
    - 80
dns:
  enable: true
  listen: 0.0.0.0:53                    #DNS监听地址
  ipv6: false
  default-nameserver:                   #解析非IP的dns用的dns服务器,只支持纯IP
    - 119.29.29.29
  enhanced-mode: fake-ip                #DNS模式(redir-host/fake-ip),【Meta专属】redir-host传递域名，可远程解析
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:                       #Fake-ip过滤，列表中的域名返回真实ip
    - "*.lan"
    #音乐版权
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    #常用网站优化
    - "+.srv.nintendo.net"
    - "+.stun.playstation.net"
    - xbox.*.microsoft.com
    - "+.xboxlive.com"
    - xbox.*.*.microsoft.com
    - "*.taobao.com"
    - "*.*.taobao.com"
    - "*.*.*.taobao.com"
    - taobao.com
    - "*.alicdn.com"
    - "*.mcdn.bilivideo.cn"
    - "*.cainiao.com"
    - "*.*.cainiao.com"
    - amap.com
    - "*.amap.com"
    - "*.snssdk.com"
    - "*.alibabausercontent.com"
    - "*.effirst.com"
    - "*.*.*.aliyuncs.com"
    - "*.alipay.com"
    - cable.auth.com
    - detectportal.firefox.com
    - global.turn.twilio.com
    - global.stun.twilio.com
    - localhost.ptlogin2.qq.com
    - "*.logon.battlenet.com.cn"
    - "*.logon.battle.net"
    - "*.blzstatic.cn"
    - proxy.golang.org
    - "*.cmpassport.com"
    - id6.me
    - open.e.189.cn
    - mdn.open.wo.cn
    - opencloud.wostore.cn
    - auth.wosms.cn
    - "*.jegotrip.com.cn"
    - "*.icitymobile.mobi"
    - "*.pingan.com.cn"
    - "*.cmbchina.com"
    - stun.*.*
    - stun.*.*.*
    #NTP服务
    - time.windows.com
    - time.nist.gov
    - time.apple.com
    - ntp.ubuntu.com
    - ntp.aliyun.com
    - ntp1.aliyun.com
    - ntp2.aliyun.com
    - ntp3.aliyun.com
    - ntp4.aliyun.com
    - ntp5.aliyun.com
    - ntp6.aliyun.com
    - ntp7.aliyun.com
    - time1.aliyun.com
    - time2.aliyun.com
    - time3.aliyun.com
    - time4.aliyun.com
    - time5.aliyun.com
    - time6.aliyun.com
    - time7.aliyun.com
    - time1.apple.com
    - time2.apple.com
    - time3.apple.com
    - time4.apple.com
    - time5.apple.com
    - time6.apple.com
    - time7.apple.com
    - time1.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com
    - time.asia.apple.com
    - "*.ntp.org.cn"
    - "*.openwrt.pool.ntp.org"
    - time1.cloud.tencent.com
    - time.ustc.edu.cn
    - pool.ntp.org
    - "*.time.edu.cn"
    #网络检测服务
    - network-test.debian.org
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - heartbeat.belkin.com
    #VPN服务
    - "*.uuuglass.*"
    - "*.iqyun.*"
    - "*.iqzone.*"
    - "*.ovoglass.*"
    - "*.iqdnsio.*"
    - "*.iqiq.*"
    #DNS服务
    - resolver1.opendns.com
    - "*.adguard-dns.*"
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "+.battlenet.com.cn"
    - "*.nextdns.*"
    - dns.google
    - "+.dns.google"
    - "*.passcloud.*"
    - dns.sb
    - "*.dns.sb"
  nameserver:
    - https://1.12.12.12/dns-query
    - https://223.5.5.5/dns-query
  fallback:
    - 'https://1.1.1.1/dns-query#DNSg'
    - 'https://doh.dns.sb/dns-query#DNSg'
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
      - 10.123.0.0/16
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'

proxies:

proxy-providers:
  HK:
    type: http
    url: ""
    interval: 86400
    path: ./HK.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  HK-F:
    type: http
    url: ""
    interval: 86400
    path: ./HK-F.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  PO-F:
    type: http
    url: ""
    interval: 86400
    path: ./PO-F.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  TW:
    type: http
    url: ""
    interval: 86400
    path: ./TW.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  SG:
    type: http
    url: ""
    interval: 86400
    path: ./SG.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  JP:
    type: http
    url: ""
    interval: 86400
    path: ./JP.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  US:
    type: http
    url: ""
    interval: 86400
    path: ./US.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  PR:
    type: http
    url: ""
    interval: 86400
    path: ./PR.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  SP:
    type: http
    url: ""
    interval: 86400
    path: ./SP.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - 香港标准节点
      - 香港节点
      - 台湾节点
      - 日本节点
      - 新加坡节点
      - 美国节点
      - 隐私节点
      - 其它节点
      - DIRECT    
  - name: 港台Bilibili
    type: select
    proxies: 
      - PASS
      - 香港标准节点
      - 香港节点
      - 台湾节点
  - name: 国际媒体
    type: select
    proxies:
      - PROXY
      - 香港标准节点
      - 香港节点
      - 台湾节点
      - 日本节点
      - 新加坡节点
      - 美国节点
      - 其它节点
  - name: 游戏加速
    type: select
    proxies:  
      - PROXY
      - 特惠节点
      - DIRECT
      - 其它节点
      - 香港标准节点
      - 台湾节点
      - 日本节点
      - 新加坡节点
      - 美国节点
  - name: 游戏下载
    type: select
    proxies: 
      - DIRECT
      - 特惠节点
      - PROXY
      - 其它节点
  - name: Speedtest
    type: select
    proxies:
      - DIRECT
      - PROXY
      - 香港标准节点
      - 香港节点
      - 台湾节点
      - 日本节点
      - 新加坡节点
      - 美国节点
      - 其它节点
  - name: Telegram
    type: select
    proxies:
      - 隐私节点
      - PROXY
      - DIRECT
  - name: Microsoft
    type: select
    proxies:
      - DIRECT
      - PASS
      - PROXY
      - 特惠节点
      - 其它节点
  - name: Bing
    type: select
    proxies:
      - PROXY
      - DIRECT
  - name: OneDrive
    type: select
    proxies:
      - DIRECT
      - 特惠节点
      - PROXY
  - name: Apple
    type: select
    proxies:
      - DIRECT
      - 特惠节点
      - PROXY
      - 其它节点
  - name: ADs
    type: select
    proxies:
      - REJECT
      - PASS
  - name: DNSg
    type: select
    proxies:
      - PROXY
      - DIRECT
  - name: 香港节点
    type: url-test
    use:
      - HK
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 香港标准节点
    type: url-test
    use:
      - HK-F
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 台湾节点
    type: url-test
    use:
      - TW
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 日本节点
    type: url-test
    use:
      - JP
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 新加坡节点
    type: url-test
    use:
      - SG
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 美国节点
    type: url-test
    use:
      - US
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 隐私节点
    type: url-test
    use:
      - PR
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 特惠节点
    type: url-test
    use:
      - PO-F
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 其它节点
    type: select
    use:
      - SP
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
rule-providers:
  #广告拦截
  Hijacking:
    type: http
    behavior: classical
    path: ./rule_provider/Hijacking.yaml
    url: https://ghproxy.com/https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Hijacking/Hijacking.yaml
    interval: 86400
  Advertising:
    type: http
    behavior: classical
    path: ./rule_provider/Advertising.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite_Classical.yaml
    interval: 86400
  #代理规则
  Global:
    type: http
    behavior: classical
    path: ./rule_provider/Global.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Proxy/Proxy.yaml
    interval: 86400
  #流媒体规则
  Streaming:
    type: http
    behavior: classical
    path: ./rule_provider/Streaming.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml
    interval: 86400
  StreamingSE:
    type: http
    behavior: classical
    path: ./rule_provider/StreamingSE.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingSE.yaml
    interval: 86400
  Bahamut:
    type: http
    behavior: classical
    path: ./rule_provider/Bahamut.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.yaml
    interval: 86400
  #直连规则
  Unbreak:
    type: http
    behavior: classical
    path: ./rule_provider/Direct.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.yaml
    interval: 86400
  China:
    type: http
    behavior: classical
    path: ./rule_provider/China.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml
    interval: 86400
  ChinaMax:
    type: http
    behavior: classical
    path: ./rule_provider/ChinaMax.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax.yaml
    interval: 86400
  ChinaMax_Domain:
    type: http
    behavior: domain
    path: ./rule_provider/ChinaMax_Domain.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Domain.yaml
    interval: 86400
  ChinaMax_IP:
    type: http
    behavior: ipcidr
    path: ./rule_provider/ChinaMax_IP.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_IP_No_IPv6.yaml
    interval: 86400
  #特殊分流规则
  Apple:
    type: http
    behavior: classical
    path: ./rule_provider/Apple.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    path: ./rule_provider/Microsoft.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
    interval: 86400
  OneDrive:
    type: http
    behavior: classical
    path: ./rule_provider/OneDrive.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.yaml
    interval: 86400
  Bing:
    type: http
    behavior: classical
    path: ./rule_provider/Bing.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/Toyro7356/Clash/release/Rules/Bing.yaml
    interval: 86400
  Speedtest:
    type: http
    behavior: classical
    path: ./rule_provider/speedtest.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.yaml
    interval: 86400
  Telegram:
    type: http
    behavior: classical
    path: ./rule_provider/Telegram.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Telegram/Telegram.yaml
    interval: 86400
  Game:
    type: http
    behavior: classical
    path: ./rule_provider/Game.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.yaml
    interval: 86400
  GameDownload:
    type: http
    behavior: classical
    path: ./rule_provider/GameDownload.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/Toyro7356/Clash/release/Rules/GameDownload.yaml
    interval: 86400
  Taobao:
    type: http
    behavior: classical
    path: ./rule_provider/Taobao.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Alibaba/Alibaba.yaml
    interval: 86400
  #特殊规则
  Special-Direct:
    type: http
    behavior: classical
    path: ./rule_provider/Special-Direct.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/Toyro7356/Clash/release/Rules/Special-Direct.yaml
    interval: 86400
  Special-Proxy:
    type: http
    behavior: classical
    path: ./rule_provider/Special-Proxy.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/Toyro7356/Clash/release/Rules/Special-Proxy.yaml
    interval: 86400
rules:
  - DST-PORT,7895,REJECT
  - DST-PORT,7892,REJECT
  - SRC-IP-CIDR,192.168.3.1/32,DIRECT
  - SRC-IP-CIDR,198.18.0.1/32,DIRECT
  - RULE-SET,Special-Direct,DIRECT
  - RULE-SET,Special-Proxy,PROXY
  - RULE-SET,Unbreak,DIRECT  
  - RULE-SET,Hijacking,ADs
  - RULE-SET,Advertising,ADs
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Bahamut,台湾节点
  - RULE-SET,Taobao,DIRECT
  - RULE-SET,Speedtest,Speedtest
  - RULE-SET,OneDrive,OneDrive
  - RULE-SET,Bing,Bing
  - RULE-SET,Apple,Apple
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,GameDownload,游戏下载
  - RULE-SET,Game,游戏加速
  - RULE-SET,StreamingSE,港台Bilibili
  - RULE-SET,Streaming,国际媒体
  - RULE-SET,China,DIRECT
  - RULE-SET,ChinaMax,DIRECT
  - RULE-SET,ChinaMax_Domain,DIRECT
  - RULE-SET,ChinaMax_IP,DIRECT
  - RULE-SET,Global,PROXY
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT
  - IP-CIDR,fe80::/10,DIRECT
  - IP-CIDR,119.28.28.28/32,DIRECT
  - IP-CIDR,182.254.116.0/24,DIRECT
  - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
